// Generated by CoffeeScript 1.9.3
(function() {
  var message, uniq;

  uniq = require("uniq");

  message = require("./message");

  console.log(message, uniq([1, 1, 1, 2, 2, 3, 3]));

}).call(this);
